# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-OC

#pod 'FDFullscreenPopGesture'
pod 'TBBaseKit', :git => 'https://gitee.com/tb-ios/TBBaseKit.git'

end
